### ISSUE TITLE
Unable to deposit Wsteth in Arbitrum Vault

### ISSUE THREAD

**Issue by TheTravel3r** [alchemix-finance/alchemix-v2-frontend#560]
### Contact Details

downstairs87@hotmail.com

### What happened?

Tried depositing Wsteth in Wsteth/weth vault on arbitrum but got error message.

### Steps to reproduce

1. Connected to alchemix on arbitrum
2. Attempted to deposit a Wsteth on Wsteth/weth vault 
3. Got error message. 
4. Cashe and cookies was already cleared. Phone already restarted.
...

### Expected behavior

To successfully deposit Wsteth into vault.
![IMG_2835](https://github.com/alchemix-finance/alchemix-v2-frontend/assets/164580773/8e3f9940-2535-4074-b459-588b2ab9d587)

### What browser were you using?

Other

### If you selected "Other" above, fill in the browser you used here.

iPhone 15 pro max Safari

**Comment by hone1er** [comment]
@n4n0GH this one should be resolved now

Not sure if the same fix handles the wstETH deposit on Optimism issue as well but might be worth testing

**Comment by TheTravel3r** [comment]
Problem still persists. Tried depositing again today, but got this error. I've tried with different wallets (metamask mobil, 1inch) and different browsers (brave desktop, iPhone 15 PM Safari, 1inch app browser, metamask app browser). Even tried with clearing cache & cookies and restarting device. No progress still. And I have plenty of gas ETH in wallet for transaction.

![image](https://github.com/alchemix-finance/alchemix-v2-frontend/assets/164580773/c0227415-c9a8-4a81-ae9a-52041b11df1c)
![image](https://github.com/alchemix-finance/alchemix-v2-frontend/assets/164580773/d2b772a3-330e-4570-902c-166a11129665)

**Comment by TheTravel3r** [comment]
Looks like I was able to deposit successfully now. Thanks! Now if not there's enough AlUSD to borrow against my deposit

**Comment by hone1er** [comment]
@TheTravel3r glad it worked! Any idea what the final error blocking you was? Or what got it to work for you?

I was thinking it wasn't working still because you tried during some peak activity and it was just hard to get the tx through or gas wasn't set properly. You may have had plenty of ETH for the transaction but if the wei and gas units aren't set correctly it can still error out. This can happen a lot when onchain activity is super high.

By the way if you deposit wstETH you wouldn't be able to borrow alUSD only alETH, which you can then swap using Ramses exchange or, if you don't mind waiting longer to ensure 1:1 exchange (like days/weeks/months longer), the transmuter. If you want an alUSD loan you have to deposit in a stablecoin vault like USDC, DAI, or Tether.

**Comment by TheTravel3r** [comment]
@hone1er hey thanks for the clarification. As for the final error, I have no idea. I just checked back for your comments of the fix and then tried again. Thanks!
